import OpenAI from 'openai'
import path from 'path'
import fs from 'fs/promises'
import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3'

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
})

const s3Client = new S3Client({
  region: process.env.AWS_REGION || 'us-east-1',
  credentials: {
    accessKeyId: process.env.AWS_ACCESS_KEY_ID || '',
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY || ''
  }
})

export interface AudioResult {
  audioBuffer: Buffer
  fileName: string
  publicUrl?: string
}

export async function generateAudioSummary(
  text: string, 
  title: string,
  maxDurationSeconds: number = 90
): Promise<AudioResult> {
  try {
    // Prepare text for TTS (limit length based on speaking rate)
    const wordsPerMinute = 150 // Average speaking rate
    const maxWords = Math.floor((maxDurationSeconds / 60) * wordsPerMinute)
    const processedText = prepareTextForTTS(text, title, maxWords)

    // Generate audio using OpenAI TTS
    const response = await openai.audio.speech.create({
      model: 'tts-1', // Use tts-1-hd for higher quality
      voice: 'nova', // Available voices: alloy, echo, fable, onyx, nova, shimmer
      input: processedText,
      response_format: 'mp3',
      speed: 1.0
    })

    // Convert response to buffer
    const arrayBuffer = await response.arrayBuffer()
    const audioBuffer = Buffer.from(arrayBuffer)
    const fileName = `audio_${Date.now()}_${Math.random().toString(36).substring(7)}.mp3`

    return {
      audioBuffer,
      fileName
    }
  } catch (error) {
    console.error('OpenAI TTS generation failed:', error)
    throw new Error('Failed to generate audio summary')
  }
}

export async function uploadAudioToStorage(
  audioBuffer: Buffer, 
  fileName: string
): Promise<string> {
  try {
    const bucketName = process.env.AWS_S3_BUCKET_NAME
    if (!bucketName) {
      console.warn('AWS_S3_BUCKET_NAME not configured, falling back to local storage')
      return await saveAudioLocally(audioBuffer, fileName)
    }

    const key = `audio/${fileName}`
    
    const command = new PutObjectCommand({
      Bucket: bucketName,
      Key: key,
      Body: audioBuffer,
      ContentType: 'audio/mpeg',
      ACL: 'public-read'
    })

    await s3Client.send(command)
    
    // Return the public URL
    const region = process.env.AWS_REGION || 'us-east-1'
    return `https://${bucketName}.s3.${region}.amazonaws.com/${key}`
    
  } catch (error) {
    console.error('S3 upload failed, falling back to local storage:', error)
    return await saveAudioLocally(audioBuffer, fileName)
  }
}

function prepareTextForTTS(text: string, title: string, maxWords: number): string {
  // Create introduction
  const intro = `Here's a summary of the article: ${title}.`
  
  // Clean and limit the main text
  let mainText = text
    .replace(/[^\w\s.,!?;:-]/g, '') // Remove special characters that might break TTS
    .replace(/\s+/g, ' ')
    .trim()

  // Split into words and limit
  const words = mainText.split(/\s+/)
  if (words.length > maxWords - 15) { // Reserve words for intro and outro
    mainText = words.slice(0, maxWords - 15).join(' ') + '.'
  }

  // Add conclusion
  const outro = 'This summary was generated by your Slack Link Bot.'

  return `${intro} ${mainText} ${outro}`
}

// Alternative: Save to local file system for development
export async function saveAudioLocally(
  audioBuffer: Buffer, 
  fileName: string
): Promise<string> {
  const publicDir = path.join(process.cwd(), 'public', 'audio')
  
  try {
    await fs.mkdir(publicDir, { recursive: true })
    const filePath = path.join(publicDir, fileName)
    await fs.writeFile(filePath, audioBuffer)
    
    return `/audio/${fileName}`
  } catch (error) {
    console.error('Local audio save failed:', error)
    throw new Error('Failed to save audio file locally')
  }
}